# **Web Scrapping Using Python**

S SURYANARAYAN

AMENU4AIE20062

AIE-A


In [ ]:
!pip install -U beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 4.6 MB/s eta 0:00:00
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.11.2
    Uninstalling beautifulsoup4-4.11.2:
      Successfully uninstalled beautifulsoup4-4.11.2


In [ ]:
from bs4 import BeautifulSoup
import re
import pandas as pd
import requests
a_c  = requests.get("http://amrita.edu")
a_c.content

b'<!DOCTYPE html>\n<html lang="en-US" prefix="og: https://ogp.me/ns#">\n<head><style>img.lazy{min-height:1px}</style><link rel="preload" href="https://www.amrita.edu/wp-content/plugins/w3-total-cache/pub/js/lazyload.min.js" as="script">\n\t<meta charset="UTF-8">\n\t<meta name="srv-index1" content="04-av" />\n\t\n\t<meta name="theme-color" content="#cd0947" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t<link rel="profile" href="https://gmpg.org/xfn/11">\n\t<link rel="pingback" href="https://www.amrita.edu/xmlrpc.php">\n\t<link rel="preconnect" href="https://fonts.googleapis.com">\n\t<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n\t<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&display=swap" rel="stylesheet">\n\t\t\t<link rel="shortcut icon" href="/wp-content/uploads/2019/05/amrita-new-favicon.ico" />\n\t\t\n<!-- Search Engine Optimization by Rank Math - https://s.rankmath.com/home -->\n<title>Amrita

In [ ]:
bs = BeautifulSoup(a_c.content)
print(bs.prettify())

<!DOCTYPE html>
<html lang="en-US" prefix="og: https://ogp.me/ns#">
 <head>
  <style>
   img.lazy{min-height:1px}
  </style>
  <link as="script" href="https://www.amrita.edu/wp-content/plugins/w3-total-cache/pub/js/lazyload.min.js" rel="preload"/>
  <meta charset="utf-8"/>
  <meta content="04-av" name="srv-index1"/>
  <meta content="#cd0947" name="theme-color"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="https://gmpg.org/xfn/11" rel="profile"/>
  <link href="https://www.amrita.edu/xmlrpc.php" rel="pingback"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&amp;display=swap" rel="stylesheet"/>
  <link href="/wp-content/uploads/2019/05/amrita-new-favicon.ico" rel="shortcut icon"/>
  <!-- Search Engine Optimization by Rank Math - https://s.rankmath.com/home -->
  <title>
   Am

In [ ]:
p = bs.find_all('p')
len(p)

25

In [ ]:
p = bs("p")
len(p)

25

In [ ]:
p[10].text

"Amrita University's Bengaluru Campus situated in Junnasandra, Karnataka, aims to create graduates with a solution mindset and a high degree of ethical standards"

In [ ]:
clss = "ts-right-text" 
content = bs.find('div', attrs = {"class":clss})
content.text

'\nLive in Labs® is a Unique Experiential Learning Program that brings together Amrita students and faculty – in conjunction with students and faculty from international universities – to form multidisciplinary teams that will spend two weeks to six months in Indian villages\n'

In [ ]:
webpage = "https://quotes.toscrape.com"
content = requests.get(webpage)
bs2 = BeautifulSoup(content.content)
bs2.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <title>\n   Quotes to Scrape\n  </title>\n  <link href="/static/bootstrap.min.css" rel="stylesheet"/>\n  <link href="/static/main.css" rel="stylesheet"/>\n </head>\n <body>\n  <div class="container">\n   <div class="row header-box">\n    <div class="col-md-8">\n     <h1>\n      <a href="/" style="text-decoration: none">\n       Quotes to Scrape\n      </a>\n     </h1>\n    </div>\n    <div class="col-md-4">\n     <p>\n      <a href="/login">\n       Login\n      </a>\n     </p>\n    </div>\n   </div>\n   <div class="row">\n    <div class="col-md-8">\n     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">\n      <span class="text" itemprop="text">\n       “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”\n      </span>\n      <span>\n       by\n       <small class="author" itemprop="author">\n        Albert Einstein\n       

In [ ]:
quote_list = []
a_list = []
q_tags = bs2.find_all('span',class_="text")
for q in q_tags:
    quote_list.append(q.text)
quote_list

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 "“I have not failed. I've just found 10,000 ways that won't work.”",
 "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
 '“A day without sunshine is like, you know, night.”']

In [ ]:
a_tags = bs2.find_all('small',class_="author")
for a in a_tags:
    a_list.append(a.text)
a_list

['Albert Einstein',
 'J.K. Rowling',
 'Albert Einstein',
 'Jane Austen',
 'Marilyn Monroe',
 'Albert Einstein',
 'André Gide',
 'Thomas A. Edison',
 'Eleanor Roosevelt',
 'Steve Martin']

In [ ]:
import pandas as pd
df = pd.DataFrame(zip(a_list,quote_list),columns = ["author","quote"])
df

author                                              quote
0    Albert Einstein  “The world as we have created it is a process ...
1       J.K. Rowling  “It is our choices, Harry, that show what we t...
2    Albert Einstein  “There are only two ways to live your life. On...
3        Jane Austen  “The person, be it gentleman or lady, who has ...
4     Marilyn Monroe  “Imperfection is beauty, madness is genius and...
5    Albert Einstein  “Try not to become a man of success. Rather be...
6         André Gide  “It is better to be hated for what you are tha...
7   Thomas A. Edison  “I have not failed. I've just found 10,000 way...
8  Eleanor Roosevelt  “A woman is like a tea bag; you never know how...
9       Steve Martin  “A day without sunshine is like, you know, nig...

In [ ]:
d = []
d.append("I am studying Natural Language processing at Amrita Amrita")
d.append("Amrita Amrita offers Natural Language Processing Processing")
d.append("Natural language processing is offered at Amrita")
d.append("It was raining yesterday")
d.append("Yesterday I learned Natural language processing in the rain")
print(d)

['I am studying Natural Language processing at Amrita Amrita', 'Amrita Amrita offers Natural Language Processing Processing', 'Natural language processing is offered at Amrita', 'It was raining yesterday', 'Yesterday I learned Natural language processing in the rain']


In [ ]:
##clean data() Pre-process
vocabulary = []
for doc in d:
    for w in doc.split():
        if w.lower() not in vocabulary:
            vocabulary.append(w.lower())
vocabulary

['i',
 'am',
 'studying',
 'natural',
 'language',
 'processing',
 'at',
 'amrita',
 'offers',
 'is',
 'offered',
 'it',
 'was',
 'raining',
 'yesterday',
 'learned',
 'in',
 'the',
 'rain']

In [ ]:
vocabulary.sort()
vocabulary

['am',
 'amrita',
 'at',
 'i',
 'in',
 'is',
 'it',
 'language',
 'learned',
 'natural',
 'offered',
 'offers',
 'processing',
 'rain',
 'raining',
 'studying',
 'the',
 'was',
 'yesterday']

In [ ]:
import numpy as np
word_vectors = []
i  = 0
for w in vocabulary :
    t = np.zeros(len(vocabulary), dtype = np.int16)
    t[i] = 1
    word_vectors.append(t)
    i = i + 1
i = 0
dic = {}
for e in word_vectors:
    print(vocabulary[i],'--->',e)
    i = i + 1


am ---> [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
amrita ---> [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
at ---> [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
i ---> [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
in ---> [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
is ---> [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
it ---> [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
language ---> [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
learned ---> [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
natural ---> [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
offered ---> [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
offers ---> [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
processing ---> [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
rain ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
raining ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
studying ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
the ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
was ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
yesterday ---> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [ ]:
text = "Amrita is studying Natural Language Processing"
text = text.lower()
text

'amrita is studying natural language processing'

In [ ]:
tokens = text.split()
tokens

['amrita', 'is', 'studying', 'natural', 'language', 'processing']

In [ ]:
doc_V = []
for e in tokens:
    doc_V.append(word_vectors[vocabulary.index(e)])

import pandas as pd
df = pd.DataFrame(doc_V)
df

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
3   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
5   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0

In [ ]:
df.columns = vocabulary
df.index = tokens
df

am  amrita  at  i  in  is  it  language  learned  natural  \
amrita       0       1   0  0   0   0   0         0        0        0   
is           0       0   0  0   0   1   0         0        0        0   
studying     0       0   0  0   0   0   0         0        0        0   
natural      0       0   0  0   0   0   0         0        0        1   
language     0       0   0  0   0   0   0         1        0        0   
processing   0       0   0  0   0   0   0         0        0        0   

            offered  offers  processing  rain  raining  studying  the  was  \
amrita            0       0           0     0        0         0    0    0   
is                0       0           0     0        0         0    0    0   
studying          0       0           0     0        0         1    0    0   
natural           0       0           0     0        0         0    0    0   
language          0       0           0     0        0         0    0    0   
processing        0       0           1     0        0         0    0    0   

            yesterday  
amrita              0  
is                  0  
studying            0  
natural             0  
language            0  
processing          0

In [ ]:
pd.get_dummies(vocabulary)

am  amrita  at  i  in  is  it  language  learned  natural  offered  \
0    1       0   0  0   0   0   0         0        0        0        0   
1    0       1   0  0   0   0   0         0        0        0        0   
2    0       0   1  0   0   0   0         0        0        0        0   
3    0       0   0  1   0   0   0         0        0        0        0   
4    0       0   0  0   1   0   0         0        0        0        0   
5    0       0   0  0   0   1   0         0        0        0        0   
6    0       0   0  0   0   0   1         0        0        0        0   
7    0       0   0  0   0   0   0         1        0        0        0   
8    0       0   0  0   0   0   0         0        1        0        0   
9    0       0   0  0   0   0   0         0        0        1        0   
10   0       0   0  0   0   0   0         0        0        0        1   
11   0       0   0  0   0   0   0         0        0        0        0   
12   0       0   0  0   0   0   0         0        0        0        0   
13   0       0   0  0   0   0   0         0        0        0        0   
14   0       0   0  0   0   0   0         0        0        0        0   
15   0       0   0  0   0   0   0         0        0        0        0   
16   0       0   0  0   0   0   0         0        0        0        0   
17   0       0   0  0   0   0   0         0        0        0        0   
18   0       0   0  0   0   0   0         0        0        0        0   

    offers  processing  rain  raining  studying  the  was  yesterday  
0        0           0     0        0         0    0    0          0  
1        0           0     0        0         0    0    0          0  
2        0           0     0        0         0    0    0          0  
3        0           0     0        0         0    0    0          0  
4        0           0     0        0         0    0    0          0  
5        0           0     0        0         0    0    0          0  
6        0           0     0        0         0    0    0          0  
7        0           0     0        0         0    0    0          0  
8        0           0     0        0         0    0    0          0  
9        0           0     0        0         0    0    0          0  
10       0           0     0        0         0    0    0          0  
11       1           0     0        0         0    0    0          0  
12       0           1     0        0         0    0    0          0  
13       0           0     1        0         0    0    0          0  
14       0           0     0        1         0    0    0          0  
15       0           0     0        0         1    0    0          0  
16       0           0     0        0         0    1    0          0  
17       0           0     0        0         0    0    1          0  
18       0           0     0        0         0    0    0          1

In [ ]:
d

['I am studying Natural Language processing at Amrita Amrita',
 'Amrita Amrita offers Natural Language Processing Processing',
 'Natural language processing is offered at Amrita',
 'It was raining yesterday',
 'Yesterday I learned Natural language processing in the rain']

In [ ]:
docV = []
for doc in d:
    dt = np.zeros(len(vocabulary), dtype = np.int16)
    for w in doc.split():
        if w.lower() in vocabulary:
            indexOfW = vocabulary.index(w.lower())
            dt[indexOfW] += 1
    docV.append(dt)
for d in docV:
    print(d)

[1 2 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0]
[0 2 0 0 0 0 0 1 0 1 0 1 2 0 0 0 0 0 0]
[0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1]
[0 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0 1]


In [ ]:
df2 = pd.DataFrame(docV)
df2.columns = vocabulary
df2

am  amrita  at  i  in  is  it  language  learned  natural  offered  offers  \
0   1       2   1  1   0   0   0         1        0        1        0       0   
1   0       2   0  0   0   0   0         1        0        1        0       1   
2   0       1   1  0   0   1   0         1        0        1        1       0   
3   0       0   0  0   0   0   1         0        0        0        0       0   
4   0       0   0  1   1   0   0         1        1        1        0       0   

   processing  rain  raining  studying  the  was  yesterday  
0           1     0        0         1    0    0          0  
1           2     0        0         0    0    0          0  
2           1     0        0         0    0    0          0  
3           0     0        1         0    0    1          1  
4           1     1        0         0    1    0          1

In [ ]:
import math
def cosSimilar(v1,v2):

    sum = 0
    lv1 = 0
    lv2 = 0
    for i in range(v1.shape[0]):
        sum += v1[i]*v2[i]
        lv1 += v1[i]*v1[i]
        lv2 += v2[i]*v2[i]
    dp = sum/(math.sqrt(lv1)*math.sqrt(lv2))
    return dp

In [ ]:
def cosSimilar2(A,B):
    res = np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
    return res

In [ ]:
A = np.array([7,7])
B = np.array([7,-7])
print(cosSimilar(A,B))
print(cosSimilar2(A,B))

0.0
0.0


In [ ]:
cosSimilar(docV[1],docV[2])

0.6837634587578276

In [ ]:
cosSimilar(docV[0],docV[4])

0.40201512610368484

In [ ]:
cosSimilar2(docV[0],docV[4])

0.40201512610368484

In [ ]:
def euclidianSimilarity(v1,v2):
    sum = 0
    for i in range(v1.shape[0]):
        sum += (v1[i]-v2[i])*(v1[i]-v2[i])
    res = 1/(1+math.sqrt(sum))
    #res = math.sqrt(sum)
    return res

In [ ]:
euclidianSimilarity(A,B)

0.06666666666666667

In [ ]:
cosSimilar2(docV[1],docV[1])

1.0

In [ ]:
euclidianSimilarity(docV[1],docV[1])

1.0

In [ ]:
def euclidianSimilarity2(v1,v2):
    res = np.sqrt(np.sum((v1-v2)**2))
    res = 1/(1+res)
    return res

In [ ]:
euclidianSimilarity2(docV[0],docV[1])

0.28989794855663564

In [ ]:
def textToVector(text):
    vec = np.zeros(len(vocabulary), dtype = np.int16)
    for w in text.split():
        if w.lower() in vocabulary:
            indexOfW = vocabulary.index(w.lower())
            vec[indexOfW] += 1
    return vec

In [ ]:
text = "Amrita is studying Natural Language Processing"
tv = textToVector(text)
tv

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
      dtype=int16)

In [ ]:
df3 = pd.DataFrame(tv)
df3.index = vocabulary
df3.transpose()

am  amrita  at  i  in  is  it  language  learned  natural  offered  offers  \
0   0       1   0  0   0   1   0         1        0        1        0       0   

   processing  rain  raining  studying  the  was  yesterday  
0           1     0        0         1    0    0          0

In [ ]:
for d in docV:
    print(cosSimilar2(d,tv))

0.7385489458759965
0.7385489458759965
0.7715167498104595
0.0
0.4082482904638631


In [ ]:
for d in docV:
    print(euclidianSimilarity2(d,tv))

0.3090169943749474
0.3090169943749474
0.36602540378443865
0.2402530733520421
0.25


# **Lab Exercise 4: Basic Vectorization**

In this lab exercise, we will vectorize the news dataset corpus using 
one-hot encoding and bag of words.

1.   For the newsdataset created from Lab 2:

*   Apply preprocessing.
*   Create one-hot encoded vectors for each token in the vocabulary.



2.   Consider each news article in the dataset as a document.

*   Apply preprocessing.
*   Create BoWs vectors for each of the documents



3.   Read a search text from the user

*   Using cosine similarity: List the top five similar documents based on the 
search text


In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load the news dataset corpus
nltk.download("brown")  # Download the Brown corpus
news_dataset = nltk.corpus.brown.sents(categories=["news"])
news_dataset = [" ".join(document) for document in news_dataset]

# Step 1: Preprocessing and One-Hot Encoding

# Apply preprocessing to the news dataset
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

preprocessed_news_dataset = []
for document in news_dataset:
    # Tokenize the document into words
    words = word_tokenize(document)
    # Remove stopwords and lemmatize words
    words = [lemmatizer.lemmatize(word.lower()) for word in words if word.isalnum() and word.lower() not in stop_words]
    # Join the words back into a single string
    preprocessed_news_dataset.append(" ".join(words))

# Create a CountVectorizer for one-hot encoding
one_hot_vectorizer = CountVectorizer(binary=True)
one_hot_vectors = one_hot_vectorizer.fit_transform(preprocessed_news_dataset)

# Step 2: Preprocessing and Bag of Words (BoWs)

# Apply preprocessing to each news article in the dataset
preprocessed_documents = []
for document in news_dataset:
    # Tokenize the document into words
    words = word_tokenize(document)
    # Remove stopwords and lemmatize words
    words = [lemmatizer.lemmatize(word.lower()) for word in words if word.isalnum() and word.lower() not in stop_words]
    # Join the words back into a single string
    preprocessed_documents.append(" ".join(words))

# Create a CountVectorizer for BoWs
bow_vectorizer = CountVectorizer()
bow_vectors = bow_vectorizer.fit_transform(preprocessed_documents)

# Step 3: Read search text and calculate cosine similarity

# Read search text from the user
search_text = input("Enter search text: ")

# Preprocess the search text
search_text_words = word_tokenize(search_text)
search_text_words = [lemmatizer.lemmatize(word.lower()) for word in search_text_words if word.isalnum() and word.lower() not in stop_words]
search_text = " ".join(search_text_words)

# Vectorize the search text using the same vectorizer used for one-hot encoding or BoWs
if one_hot_vectorizer.vocabulary_.get(search_text) is not None:
    search_vector = one_hot_vectorizer.transform([search_text])
else:
    search_vector = bow_vectorizer.transform([search_text])

# Calculate cosine similarity between search vector and document vectors
similarity_scores = cosine_similarity(search_vector, bow_vectors)

# Get indices of top 5 similar documents
top_indices = similarity_scores.argsort()[0][-5:][::-1]

# Print the top 5 similar documents
print("Top 5 similar documents based on the search text:")
for index in top_indices:
    print(news_dataset[index])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.


Enter search text: VECTOR
Top 5 similar documents based on the search text:
This is one of the main reasons for National Library Week , April 16-22 , and for its theme : `` For a richer , fuller life , read '' ! !
Arnold's iron shot from the tee burrowed into the bunker guarding the green , an embankment that had become soft and spongy from the rains , thereby bringing local rules into force .
Other lettermen from the team that compiled a 21-9 record and finished as runner-up in the National Invitation Tournament were : Art Hambric , Donnell Reid , Bill Nordmann , Dave Harris , Dave Luechtefeld and George Latinovich .
`` This team set a precedent that could be valuable in the future '' , Benington pointed out .
`` By winning against Bradley , Kentucky and Notre Dame on those teams' home courts , they showed that the home court advantage can be overcome anywhere and that it doesn't take a super team to do it '' .
